[build]
  command = "npm ci && npm run build && cp _redirects.${NETLIFY_CONTEXT} dist/_redirects"
  publish = "dist"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  VITE_API_URL = "https://club-attendance.com/api"

[context.staging.environment]
  VITE_API_URL = "https://staging.clubattendance.example/api"
